services:
  db:
    image: postgres:18
    environment:
      POSTGRES_DB: 'ecmorelia_db'
      POSTGRES_USER: 'posgres'
      POSTGRES_PASSWORD: '1234'
    ports:
      - '5432:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
